version: '3.7'

services:
  postgres:
    container_name: postgres-local
    environment:
      - POSTGRES_PASSWORD=loan
      - POSTGRES_USER=loan
    image: postgres:13.5-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis-local
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  loan-app:
    container_name: loan-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    env_file:
      - .env
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/loan-app
    depends_on:
      - postgres
      - redis
    stdin_open: true
    tty: true

volumes:
  postgres-data:
  redis-data: