default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: loan_app_development

test:
  <<: *default
  database: loan_app_test

production:
  <<: *default
  database: loan_app_production
  username: loan_app
  password: <%= ENV["LOAN_APP_DATABASE_PASSWORD"] %>
